import { useEffect, useState } from 'react';
import client from '../api/client';

export default function BudgetSummary() {
  const [summary, setSummary] = useState([]); const [newCategoryName, setNewCategoryName] = useState(''); const [newBudget, setNewBudget] = useState(''); const [error, setError] = useState('');
  async function fetchSummary() { try { const { data } = await client.get('/budgets/summary'); setSummary(data); } catch (requestError) { setError(requestError.response?.data?.error || 'Could not load budgets'); } }
  useEffect(() => { fetchSummary(); }, []);
  async function handleAddCategory(event) { event.preventDefault(); if (!newCategoryName.trim()) return; try { await client.post('/budgets/categories', { name: newCategoryName, monthly_budget: newBudget ? parseFloat(newBudget) : null }); setNewCategoryName(''); setNewBudget(''); await fetchSummary(); } catch (requestError) { setError(requestError.response?.data?.error || 'Could not add category'); } }
  async function handleUpdateBudget(id, value) { try { await client.patch(`/budgets/categories/${id}/budget`, { monthly_budget: value ? parseFloat(value) : null }); await fetchSummary(); } catch (requestError) { setError(requestError.response?.data?.error || 'Could not update budget'); } }
  return <section className="budget-summary panel"><div className="panel-title"><div><span className="eyebrow">Plan against reality</span><h2>Budget vs. actual</h2></div><span className="budget-month">This month</span></div>{error && <p className="notice">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Category</th><th>Budget</th><th>Spent</th><th>Status</th></tr></thead><tbody>{summary.map((row) => <tr key={row.id} className={row.over_budget ? 'over-budget' : ''}><td><strong>{row.name}</strong></td><td><input className="budget-input" type="number" min="0" step="0.01" defaultValue={row.monthly_budget ?? ''} placeholder="No budget" onBlur={(event) => handleUpdateBudget(row.id, event.target.value)} /></td><td>${row.actual_spent.toFixed(2)}</td><td>{row.monthly_budget !== null ? row.over_budget ? <span className="status-over">Over by ${(row.actual_spent - row.monthly_budget).toFixed(2)}</span> : <span className="status-good">${(row.monthly_budget - row.actual_spent).toFixed(2)} left</span> : <span className="status-none">No budget set</span>}</td></tr>)}</tbody></table>{!summary.length && <p className="empty-state">Add a category to start planning.</p>}</div><form onSubmit={handleAddCategory} className="add-category-form"><input placeholder="New category name" value={newCategoryName} onChange={(event) => setNewCategoryName(event.target.value)} /><input type="number" min="0" step="0.01" placeholder="Monthly budget" value={newBudget} onChange={(event) => setNewBudget(event.target.value)} /><button className="primary-button" type="submit">Add category</button></form></section>;
}