import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const { login, error, loading } = useAuth(); const navigate = useNavigate();
  async function handleSubmit(event) { event.preventDefault(); if (await login(email, password)) navigate('/dashboard'); }
  return <AuthLayout eyebrow="Welcome back" title="Your money, in focus." subtitle="Sign in to see the shape of your financial life."><form className="auth-form" onSubmit={handleSubmit}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="you@example.com" /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required placeholder="Your password" /></label>{error && <p className="error">{error}</p>}<button className="primary-button" type="submit" disabled={loading}>{loading ? 'Logging in...' : 'Log in'}</button></form><p className="auth-switch">New to Ledgerly? <Link to="/signup">Create an account</Link></p></AuthLayout>;
}
export function AuthLayout({ eyebrow, title, subtitle, children }) { return <main className="auth-page"><section className="auth-visual"><span className="brand"><span className="brand-mark">L</span> ledgerly</span><div className="visual-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><span className="visual-note">Personal finance, made legible.</span></section><section className="auth-panel"><div className="auth-content"><span className="eyebrow">Private dashboard</span><h2>{title}</h2><p className="auth-intro">Everything you need to make calmer money decisions.</p>{children}</div></section></main>; }